apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qeypzmaud-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qeypzmaud-python 
  name: qeypzmaud-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qeypzmaud-python 
